---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-maps
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-maps
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-maps
    spec:
      volumes:
      containers:
      - name: workadventure
        image:  {{ .Values.image_maps }}
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            memory: 1000Mi
        env:
        - name: DEBUG_MODE
          value: {{ .Values.debug_mode | quote }}
        - name: HOST
          value: "0.0.0.0"
     