---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-website
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-website
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-website
    spec:
      volumes:
      containers:
      - name: workadventure
        image: {{ .Values.image_website }}
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            memory: 1000Mi
