{{ if (default .Values.ingress.enabled true)}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  annotations: 
    {{- if .Values.ingress.annotations }}
    {{- include "map.render" (dict "value" .Values.ingress.annotations "context" $) | nindent 4 }}
    {{- end }}
spec:
  {{ if (default .Values.tls.enabled true)}}
  tls:
  - hosts:
    - {{ .Values.dns.wildcard | quote }}
    - {{ .Values.dns.website | quote }}
    secretName: {{ .Values.tls.secretName }} 
  {{ end }}
  rules:
  - host: {{ .Values.dns.play }}
    http:
      paths:
      - backend:
          serviceName: {{ .Chart.Name }}-front
          servicePort: 80
  - host: {{ .Values.dns.maps}} 
    http:
      paths:
      - backend:
          serviceName: {{ .Chart.Name }}-maps
          servicePort: 80
  - host: {{ .Values.dns.api }}
    http:
      paths:
      - backend:
          serviceName: {{ .Chart.Name }}-back
          servicePort: 8080
  - host: {{ .Values.dns.website }}
    http:
      paths:
      - backend:
          serviceName: {{ .Chart.Name }}-website
          servicePort: 80
{{ end }}

