apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
type: Opaque
data:
  secret_jitsi_key: {{ .Values.env.secrets.secret_jitsi_key | b64enc }}
  secret_key: {{ .Values.env.secrets.secret_key | b64enc }}
  admin_api_token: {{ .Values.env.secrets.admin_api_token | b64enc }}

